### PR TITLE
Only one HostsResolver per hosts file

### LINKED ISSUE #25: Memory leak each time cachableLookup is imported and constructed.
Hi! 

I think I've stumbled into a memory leak in cacheable lookup. This leak is present in [got](https://github.com/sindresorhus/got/issues/1220), as well as other libraries that are using `got`, such as webdriver.io.

```ts
const CL = require('cacheable-lookup');
new CL();
```

I'm working on a standalone example to help reproduce the problem.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #25

### CODE REVIEW

**Comment by szmarczak** [comment]
@dylang What do you think about this?

**Comment by dylang** [comment]
This does not solve the memory issue.

**Comment by dylang** [comment]
I think it doesn't solve the problem in this part of the code:

```js
this._promise = (async () => {
			if (typeof this._hostsPath !== 'string') {
				return;
			}

			await this._update();

			if (this._error) {
				return;
			}

			watchFile(this._hostsPath, {
				persistent: false
			}, (current, previous) => {
				if (current.mtime > previous.mtime) {
					this._update();
				}
			}).once('error', error => {
				this._error = error;
				this._hosts = {};
			});

			this._promise = null;
		})();
```

Can `watchFile` be opt-in instead of opt-out?

What stops `watchFile`?

**Comment by szmarczak** [comment]
> What stops watchFile?

Simply pass `dnsCache: new CacheableLookup({customHostsPath: false})` or `dnsCache: false`.

**Comment by szmarczak** [comment]
> Can watchFile be opt-in instead of opt-out?

Yep, will do this tomorrow.

**Comment by dylang** [comment]
> Simply pass dnsCache: new CacheableLookup({customHostsPath: false}) or dnsCache: false.

That prevents it, but once `watchFile` starts watching, what swill stop it from watching, other than killing the process?

Also, unrelated, using fs.watch() is more efficient than fs.watchFile()
https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener

**Comment by szmarczak** [comment]
> what will stop it from watching, other than killing the process?

Unfortunately there are no destructors in JS.
That's why I implemented in this PR some sort of singletons.

> Also, unrelated, using fs.watch() is more efficient than fs.watchFile()

Thanks, didn't know that! But this doesn't fix the memory leak either, does it?

**Comment by dylang** [comment]
> Unfortunately there are no destructors in JS.

Correct. This is why it might be better to export a method to start and stop the watcher.

**Pull request merged**
